/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputWithFocus {
    }
    interface MyComponent {
    }
}
declare global {
    interface HTMLInputWithFocusElement extends Components.InputWithFocus, HTMLStencilElement {
    }
    var HTMLInputWithFocusElement: {
        prototype: HTMLInputWithFocusElement;
        new (): HTMLInputWithFocusElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "input-with-focus": HTMLInputWithFocusElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface InputWithFocus {
    }
    interface MyComponent {
    }
    interface IntrinsicElements {
        "input-with-focus": InputWithFocus;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-with-focus": LocalJSX.InputWithFocus & JSXBase.HTMLAttributes<HTMLInputWithFocusElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
